date: today
date-format: long
execute:
  echo: false
  enabled: true
format:
  dashboard:
    embed-resources: true
    link-external-newwindow: true
    scrolling: true
jupyter: python3
output-file: A1234_Summary_20240730-121216Z.html
project:
  output-dir: C:\Users\CORK-LAB9\Downloads\DATA_Reports_Self_path/
theme: custom.scss
title: Summary for A1234
